"""15 ta o'quvchi loyihasining rejalari. build.py shu ma'lumotdan Markdown fayllar va HTML sahifa yasaydi."""

LEVELS = {1: "Boshlang'ich", 2: "O'rta", 3: "Murakkab"}

PROJECTS = [
    {
        "slug": "lugat-bot",
        "title": "So'zBot — inglizcha so'z yodlash",
        "level": 1, "weeks": 2, "team": "1–2 o'quvchi",
        "problem": "O'quvchilar yangi so'zlarni yodlaydi, lekin takrorlamagani uchun tez unutadi.",
        "users": "Ingliz tilini o'rganayotgan o'quvchilar",
        "features": [
            "Har kuni soat 08:00 da 5 ta yangi so'z (so'z, tarjima, misol gap)",
            "/test — 5 ta savol, 4 ta variantli tugmalar bilan",
            "Xato javob berilgan so'zlar 1, 3 va 7 kundan keyin qayta so'raladi",
            "/natija — to'g'ri javoblar foizi va ketma-ket kunlar (streak)",
        ],
        "commands": ["/start", "/bugun", "/test", "/natija", "/daraja A1|A2|B1"],
        "tables": [
            "users: telegram_id, ism, daraja, streak, oxirgi_kun",
            "words: so'z, tarjima, misol, daraja",
            "answers: user_id, word_id, to'g'ri (0/1), sana, keyingi_takror",
        ],
        "steps": [
            "1-hafta: 200 ta so'zni CSV faylga yig'ish, /start va /bugun, inline tugmali test",
            "2-hafta: takrorlash jadvali (1-3-7 kun), har kungi xabar, /natija",
        ],
        "bonus": ["So'zning talaffuzi (ovozli xabar)", "Sinf bo'yicha haftalik reyting"],
        "skills": ["aiogram: buyruqlar va inline tugmalar", "CSV o'qish", "SQLite", "sana bilan ishlash"],
        "money": "Bepul: kuniga 5 so'z. Premium (5 000 so'm/oy): IELTS so'z to'plamlari va cheksiz test.",
    },
    {
        "slug": "kitobxon",
        "title": "Kitobxon kundaligi",
        "level": 1, "weeks": 2, "team": "1–2 o'quvchi",
        "problem": "Kitob o'qish odatini kuzatish va o'zini rag'batlantirish qiyin.",
        "users": "Barcha sinf o'quvchilari, kutubxonachi",
        "features": [
            "/kitob — o'qilayotgan kitob nomi va jami sahifa soni",
            "/oqidim 25 — bugun o'qilgan sahifalar; progress foizda ko'rsatiladi",
            "Kechqurun 20:00 da \"Bugun o'qidingmi?\" eslatmasi",
            "Kitob tugaganda 1–5 baho va bir gapli fikr qoldirish",
        ],
        "commands": ["/start", "/kitob", "/oqidim", "/statistika", "/tavsiya"],
        "tables": [
            "users: telegram_id, ism, sinf",
            "books: user_id, nomi, muallif, jami_sahifa, tugadi",
            "reading_log: book_id, sana, sahifalar",
            "reviews: book_id, baho, fikr",
        ],
        "steps": [
            "1-hafta: kitob qo'shish, sahifa yozish, progress foizi",
            "2-hafta: kechki eslatma, oylik statistika, boshqalar baho bergan kitoblar ro'yxati (/tavsiya)",
        ],
        "bonus": ["Oyning eng ko'p o'qigan o'quvchisi", "Kitob yakunlanganda sertifikat rasmi (Pillow)"],
        "skills": ["FSM (bosqichma-bosqich so'rash)", "rejalashtirilgan xabarlar", "SQL GROUP BY"],
        "money": "Maktab kutubxonasi uchun yillik obuna: sinflar reytingi va hisobotlar.",
    },
    {
        "slug": "misol-trenajyor",
        "title": "Misol trenajyori",
        "level": 1, "weeks": 2, "team": "1 o'quvchi",
        "problem": "Og'zaki hisobni mashq qilish zerikarli, natijani hech kim kuzatmaydi.",
        "users": "1–7-sinf o'quvchilari",
        "features": [
            "Daraja tanlash: qo'shish/ayirish, ko'paytirish jadvali, kasrlar, tenglamalar",
            "60 soniyalik raund: tasodifiy misollar, javob yoziladi",
            "Har to'g'ri javobga ball, ketma-ket to'g'ri javobga bonus",
            "/top — sinf va maktab bo'yicha eng yaxshi 10 natija",
        ],
        "commands": ["/start", "/oyin", "/daraja", "/top", "/mening"],
        "tables": [
            "users: telegram_id, ism, sinf",
            "games: user_id, daraja, ball, togri, xato, sana",
        ],
        "steps": [
            "1-hafta: misol generatori (random), javobni tekshirish, ball",
            "2-hafta: vaqtli raund, reyting jadvali, darajalar",
        ],
        "bonus": ["Ikki o'quvchi o'rtasida duel", "Xato qilingan misol turlari tahlili"],
        "skills": ["random moduli", "vaqtni o'lchash", "funksiyalarni testlash (unittest)"],
        "money": "Repetitorlar uchun pullik versiya: o'z o'quvchilari natijalarini ko'rish paneli.",
    },
    {
        "slug": "oshxona-menyu",
        "title": "Maktab oshxonasi menyusi",
        "level": 1, "weeks": 2, "team": "2 o'quvchi",
        "problem": "O'quvchi va ota-onalar bugun oshxonada nima borligini va narxini bilmaydi.",
        "users": "O'quvchilar, ota-onalar, oshxona mudiri",
        "features": [
            "Admin (oshxona mudiri) haftalik menyuni narxi bilan kiritadi",
            "/bugun va /hafta — menyu ko'rinishida",
            "Taomga 👍/👎 ovoz berish, haftaning eng yoqqan taomi",
            "Allergiya belgisi: tarkibida yong'oq, sut va boshqalar bor taomlar ajratiladi",
        ],
        "commands": ["/start", "/bugun", "/hafta", "/ovoz", "/admin_menu"],
        "tables": [
            "dishes: nomi, narx, tarkib, allergenlar",
            "menu: sana, dish_id",
            "votes: user_id, dish_id, sana, qiymat",
        ],
        "steps": [
            "1-hafta: admin rejimi va menyu kiritish, /bugun, /hafta",
            "2-hafta: ovoz berish, haftalik natija, allergen filtri",
        ],
        "bonus": ["Taom rasmi bilan menyu", "Oldindan buyurtma berish (navbatsiz)"],
        "skills": ["admin huquqlarini tekshirish", "rasm yuborish", "ovozlarni hisoblash"],
        "money": "Oldindan buyurtma funksiyasi uchun oshxonadan har buyurtmaga kichik komissiya.",
    },
    {
        "slug": "imtihon-sanoq",
        "title": "Imtihon sanog'i va reja",
        "level": 1, "weeks": 2, "team": "1–2 o'quvchi",
        "problem": "Imtihon yaqinlashganini o'quvchi oxirgi haftada sezadi, tayyorgarlik rejasi yo'q.",
        "users": "9- va 11-sinf o'quvchilari, abituriyentlar",
        "features": [
            "Imtihon nomi va sanasini kiritish; har kuni \"qolgan kunlar\" xabari",
            "Mavzular ro'yxatini kiritsa, bot ularni qolgan kunlarga teng bo'lib reja tuzadi",
            "/bajardim — bugungi mavzu belgilanadi, progress ko'rsatiladi",
            "Har yakshanba haftalik hisobot",
        ],
        "commands": ["/start", "/imtihon", "/mavzular", "/bugun", "/bajardim", "/hisobot"],
        "tables": [
            "exams: user_id, nomi, sana",
            "topics: exam_id, nomi, reja_sanasi, bajarildi",
        ],
        "steps": [
            "1-hafta: imtihon va mavzular, kunlarga taqsimlash algoritmi",
            "2-hafta: kunlik xabar, belgilash, haftalik hisobot",
        ],
        "bonus": ["Bajarilmagan mavzuni keyingi kunlarga avtomatik ko'chirish", "Motivatsion iqtiboslar"],
        "skills": ["timedelta bilan hisoblash", "ro'yxatni teng bo'lish algoritmi", "rejalashtiruvchi"],
        "money": "O'quv markazlari bilan hamkorlik: tayyor mavzular rejalari pullik paket sifatida.",
    },
    {
        "slug": "quiz-bot",
        "title": "Sinf viktorinasi (Quiz) boti",
        "level": 2, "weeks": 3, "team": "2 o'quvchi",
        "problem": "O'qituvchi tez test o'tkazib, natijani darhol ko'rishni xohlaydi.",
        "users": "O'qituvchi (test tuzadi), o'quvchilar (yechadi)",
        "features": [
            "O'qituvchi savollarni matn yoki Excel fayl orqali yuklaydi",
            "Test kodi beriladi; o'quvchi /test KOD bilan kiradi",
            "Har savolga vaqt chegarasi, javoblar aralashtiriladi",
            "O'qituvchiga natijalar jadvali va Excel fayl",
        ],
        "commands": ["/start", "/yangi_test", "/savol_qosh", "/test", "/natijalar"],
        "tables": [
            "quizzes: teacher_id, nomi, kod, savol_vaqti, faol",
            "questions: quiz_id, matn, variantlar, togri_index",
            "attempts: quiz_id, student_id, ball, boshlandi, tugadi",
            "answers: attempt_id, question_id, tanlov, togri",
        ],
        "steps": [
            "1-hafta: test va savol yaratish, test kodi",
            "2-hafta: o'quvchi testni yechadi, vaqt chegarasi, ball",
            "3-hafta: Excel import/eksport (openpyxl), natijalar jadvali",
        ],
        "bonus": ["Telegram guruhida jonli viktorina (Kahoot uslubida)", "Savol rasmlari"],
        "skills": ["rollar (o'qituvchi/o'quvchi)", "openpyxl", "FSM", "taymerlar"],
        "money": "Start: oyiga 5 ta test bepul; Pro o'qituvchi: cheksiz test va Excel hisobot.",
    },
    {
        "slug": "davomat",
        "title": "Davomat boti",
        "level": 2, "weeks": 3, "team": "2 o'quvchi",
        "problem": "Ota-ona farzandi darsga kelmaganini kechqurun yoki umuman bilmaydi.",
        "users": "Sinf rahbari yoki sardori, ota-onalar",
        "features": [
            "Sinf ro'yxati bir marta kiritiladi",
            "Ertalab tugmalar bilan \"keldi / kelmadi / kechikdi\" belgilanadi",
            "Kelmagan o'quvchining ota-onasiga darhol Telegram xabar",
            "Oylik davomat foizi va eng ko'p qoldirganlar ro'yxati",
        ],
        "commands": ["/start", "/sinf", "/davomat", "/hisobot", "/ota_ona KOD"],
        "tables": [
            "classes: nomi, rahbar_id",
            "students: class_id, ism, ota_ona_telegram_id, ulanish_kodi",
            "attendance: student_id, sana, holat",
        ],
        "steps": [
            "1-hafta: sinf va o'quvchilar, ota-onani kod orqali ulash",
            "2-hafta: tugmali davomat, ota-onaga xabar",
            "3-hafta: oylik hisobot, Excel eksport",
        ],
        "bonus": ["Sababli/sababsiz izohi", "Ketma-ket 3 kun kelmasa sinf rahbariga ogohlantirish"],
        "skills": ["ko'p tugmali inline klaviatura", "foydalanuvchilarni bog'lash", "maxfiylik"],
        "money": "Maktab uchun oylik litsenziya; ota-ona uchun bepul.",
    },
    {
        "slug": "vazifa-daftari",
        "title": "O'quvchining vazifa daftari",
        "level": 2, "weeks": 3, "team": "1–2 o'quvchi",
        "problem": "O'quvchi qaysi fandan qanday vazifa va qachongacha berilganini unutadi.",
        "users": "O'quvchilar (UstozBot'ning o'quvchi tomoni)",
        "features": [
            "Vazifa qo'shish: fan, matn, muddat, rasm (doska surati)",
            "Ertaga topshiriladigan vazifalar har kuni 19:00 da",
            "Bajarilganini belgilash, kechikkanlar qizil ro'yxatda",
            "Sinfdoshlar bilan umumiy sinf daftari (bir kishi kiritadi, hamma ko'radi)",
        ],
        "commands": ["/start", "/qosh", "/ertaga", "/hafta", "/bajardim", "/sinfga_qoshil KOD"],
        "tables": [
            "users: telegram_id, ism, class_code",
            "homeworks: class_code, fan, matn, rasm_file_id, muddat, muallif_id",
            "done: user_id, homework_id",
        ],
        "steps": [
            "1-hafta: shaxsiy vazifa qo'shish va ro'yxat",
            "2-hafta: kechki eslatma, bajarilganlar",
            "3-hafta: umumiy sinf daftari, rasm saqlash (file_id)",
        ],
        "bonus": ["Dars jadvalidan fanni avtomatik taklif qilish", "UstozBot bilan bog'lash"],
        "skills": ["Telegram file_id bilan ishlash", "guruh kodi orqali umumiy ma'lumot", "eslatmalar"],
        "money": "Bepul; sinf uchun reklama yo'q Pro versiya — 3 000 so'm/oy.",
    },
    {
        "slug": "elonlar",
        "title": "Maktab e'lonlari va to'garaklar",
        "level": 2, "weeks": 3, "team": "2–3 o'quvchi",
        "problem": "Tadbir va to'garaklar haqida e'lonlar devorda qoladi, ko'pchilik ko'rmaydi.",
        "users": "O'quvchilar, ota-onalar, maktab ma'muriyati",
        "features": [
            "Admin e'lon yozadi: matn, rasm, sana; bot obunachilarga tarqatadi",
            "Obuna toifalari: sport, fan to'garaklari, tadbirlar, umumiy",
            "To'garakka ro'yxatdan o'tish (joylar soni cheklangan)",
            "Tadbirdan bir kun oldin eslatma",
        ],
        "commands": ["/start", "/obuna", "/elonlar", "/togaraklar", "/yozilish", "/admin_elon"],
        "tables": [
            "users: telegram_id, ism, sinf, rol",
            "subscriptions: user_id, toifa",
            "posts: toifa, matn, rasm, tadbir_sanasi",
            "clubs: nomi, rahbar, vaqt, joylar",
            "signups: club_id, user_id",
        ],
        "steps": [
            "1-hafta: obuna toifalari, admin e'lon va tarqatish",
            "2-hafta: to'garaklar va ro'yxatdan o'tish",
            "3-hafta: tadbir eslatmalari, statistika",
        ],
        "bonus": ["Telegram kanalga avtomatik joylash", "So'rovnoma (poll) natijalari"],
        "skills": ["ommaviy xabar yuborish va limitlar", "obunalar", "cheklangan joylar mantiqi"],
        "money": "Xususiy to'garaklar va o'quv markazlari uchun pullik e'lon joylash.",
    },
    {
        "slug": "topilmalar",
        "title": "Yo'qolgan buyumlar boti",
        "level": 2, "weeks": 3, "team": "2 o'quvchi",
        "problem": "Maktabda yo'qolgan buyum egasini topish uchun hamma joyni so'rab chiqish kerak.",
        "users": "O'quvchilar, navbatchi o'qituvchi",
        "features": [
            "\"Yo'qotdim\" va \"Topdim\" e'lonlari: rasm, toifa, joy, sana",
            "Toifa va kalit so'z bo'yicha qidiruv",
            "Yangi \"topildi\" e'loni mos \"yo'qotdim\" egasiga avtomatik xabar beradi",
            "Moderator e'lonni tasdiqlaydi; egasiga qaytgach yopiladi",
        ],
        "commands": ["/start", "/yoqotdim", "/topdim", "/qidir", "/menikilar"],
        "tables": [
            "items: turi (lost/found), toifa, tavsif, rasm, joy, sana, holat, egasi_id",
            "matches: lost_id, found_id, xabar_yuborildi",
        ],
        "steps": [
            "1-hafta: e'lon qo'shish FSM orqali, rasm",
            "2-hafta: qidiruv, moderatsiya",
            "3-hafta: avtomatik moslashtirish (toifa + kalit so'zlar)",
        ],
        "bonus": ["30 kundan eski e'lonlarni arxivlash", "Topgan o'quvchiga \"rahmat\" ballari"],
        "skills": ["matn bo'yicha qidiruv (LIKE)", "moderatsiya oqimi", "oddiy moslashtirish algoritmi"],
        "money": "Ijtimoiy loyiha: daromad emas, maktab tanlovlari va grantlar uchun portfolio.",
    },
    {
        "slug": "kutubxona",
        "title": "Maktab kutubxonasi boti",
        "level": 3, "weeks": 4, "team": "2–3 o'quvchi",
        "problem": "Kitob bor-yo'qligini bilish uchun kutubxonaga borish kerak, qaytarish muddati unutiladi.",
        "users": "O'quvchilar, kutubxonachi",
        "features": [
            "Katalog: nomi, muallif, nusxalar soni bo'yicha qidiruv",
            "Kitobni band qilish; kutubxonachi berilganini tasdiqlaydi",
            "Qaytarish muddatidan 2 kun oldin va kechikkanda eslatma",
            "Band qilingan kitob qaytsa navbatdagi o'quvchiga xabar",
        ],
        "commands": ["/start", "/qidir", "/band", "/kitoblarim", "/admin_ber", "/admin_qaytdi"],
        "tables": [
            "books: nomi, muallif, isbn, nusxalar, mavjud",
            "loans: book_id, user_id, berildi, muddat, qaytdi",
            "reservations: book_id, user_id, sana, navbat",
        ],
        "steps": [
            "1-hafta: katalog import (Excel), qidiruv",
            "2-hafta: band qilish va berish/qaytarish",
            "3-hafta: muddat eslatmalari, navbat",
            "4-hafta: statistika: eng ko'p o'qilgan kitoblar, qarzdorlar",
        ],
        "bonus": ["Telegram Mini App ko'rinishidagi katalog", "ISBN orqali kitob muqovasini olish"],
        "skills": ["tranzaksiyalar (nusxalar soni)", "navbat mantiqi", "Excel import"],
        "money": "Maktab va xususiy kutubxonalar uchun yillik obuna.",
    },
    {
        "slug": "ustoz-shogird",
        "title": "Ustoz–shogird (o'zaro yordam) boti",
        "level": 3, "weeks": 4, "team": "2–3 o'quvchi",
        "problem": "Fandan qiynalayotgan o'quvchi yordam so'rashga tortinadi, kuchli o'quvchilar esa yordam berishga tayyor.",
        "users": "O'quvchilar (yordam so'raydi / yordam beradi), sinf rahbari",
        "features": [
            "O'quvchi qaysi fan va mavzudan kuchli ekanini belgilaydi",
            "Yordam so'rovi: fan, mavzu, qulay vaqt; mos yordamchilarga yuboriladi",
            "Uchrashuv qabul qilingach ikkalasiga eslatma",
            "Uchrashuvdan keyin baho; yordamchilar reytingi va ballari",
        ],
        "commands": ["/start", "/men_bilaman", "/yordam_kerak", "/sorovlar", "/uchrashuvlarim", "/reyting"],
        "tables": [
            "users: telegram_id, ism, sinf",
            "skills: user_id, fan, mavzu",
            "requests: student_id, fan, mavzu, vaqt, holat, helper_id",
            "ratings: request_id, baho, izoh",
        ],
        "steps": [
            "1-hafta: profil va ko'nikmalar",
            "2-hafta: so'rov yaratish va mos yordamchilarga tarqatish",
            "3-hafta: qabul qilish, eslatmalar",
            "4-hafta: baho, reyting, oylik eng faol yordamchi",
        ],
        "bonus": ["Anonim savol berish", "Ballarni maktab sovg'alariga almashtirish"],
        "skills": ["moslashtirish (matching)", "holatlar mashinasi", "xavfsizlik: shaxsiy ma'lumotni yashirish"],
        "money": "Bitiruvchi va talabalar uchun pullik repetitor bo'limi, har darsdan komissiya.",
    },
    {
        "slug": "olimpiada",
        "title": "Olimpiadaga tayyorgarlik trekeri",
        "level": 3, "weeks": 4, "team": "2–3 o'quvchi",
        "problem": "Olimpiadaga tayyorlanayotgan o'quvchilar masala yechishini murabbiy kuzatib bora olmaydi.",
        "users": "Olimpiadachilar, fan murabbiyi",
        "features": [
            "Murabbiy haftalik masalalar to'plamini qo'shadi (matn yoki PDF)",
            "O'quvchi yechimni rasm yoki matn bilan yuboradi",
            "Murabbiy baholaydi va izoh yozadi",
            "Reyting jadvali, kunlik mashq streaki, tanlovgacha qolgan kunlar",
        ],
        "commands": ["/start", "/masalalar", "/yechim", "/baholash", "/reyting", "/streak"],
        "tables": [
            "problems: fan, sarlavha, matn_yoki_fayl, ball, hafta",
            "submissions: problem_id, user_id, fayl, matn, ball, izoh, sana",
            "contests: nomi, sana",
        ],
        "steps": [
            "1-hafta: masalalar to'plami, rollar",
            "2-hafta: yechim yuborish (rasm/PDF)",
            "3-hafta: baholash oqimi, izohlar",
            "4-hafta: reyting, streak, tanlov sanog'i",
        ],
        "bonus": ["Avtomatik tekshiriladigan javobli masalalar", "Haftalik eng yaxshi yechim kanalga"],
        "skills": ["fayllar bilan ishlash", "ko'p bosqichli tekshiruv oqimi", "reyting formulasi"],
        "money": "Murabbiylar uchun Pro tarif: cheksiz o'quvchi va masala bazasi.",
    },
    {
        "slug": "uchrashuv-navbati",
        "title": "Ota-ona — o'qituvchi uchrashuv navbati",
        "level": 3, "weeks": 4, "team": "2–3 o'quvchi",
        "problem": "Ota-onalar majlisida hammasi bir vaqtda keladi, o'qituvchi bilan alohida gaplashish uchun uzoq navbat.",
        "users": "O'qituvchilar (vaqt ochadi), ota-onalar (band qiladi)",
        "features": [
            "O'qituvchi bo'sh vaqt oraliqlarini ochadi (masalan, 15 daqiqalik slotlar)",
            "Ota-ona o'qituvchi va bo'sh slotni tanlaydi",
            "Bir slotni ikki kishi band qila olmaydi; bekor qilish mumkin",
            "Uchrashuvdan 1 kun va 1 soat oldin eslatma",
        ],
        "commands": ["/start", "/oqituvchilar", "/band_qilish", "/uchrashuvlarim", "/slot_och", "/bekor"],
        "tables": [
            "teachers: telegram_id, ism, fan",
            "slots: teacher_id, boshlanish, tugash, holat",
            "bookings: slot_id, parent_id, farzand_ismi, izoh",
        ],
        "steps": [
            "1-hafta: o'qituvchi slot ochadi",
            "2-hafta: ota-ona band qiladi, ikki marta band qilishni oldini olish",
            "3-hafta: eslatmalar, bekor qilish",
            "4-hafta: kunlik jadval o'qituvchiga, statistika",
        ],
        "bonus": ["Onlayn uchrashuv havolasi (Google Meet) qo'shish", "Uchrashuvdan keyin qisqa so'rovnoma"],
        "skills": ["vaqt oraliqlari bilan ishlash", "poyga holati (race condition)", "eslatmalar"],
        "money": "Xususiy maktablar va o'quv markazlari uchun oylik obuna.",
    },
    {
        "slug": "eko-musobaqa",
        "title": "Eko-musobaqa: makulatura va plastik yig'ish",
        "level": 3, "weeks": 4, "team": "3 o'quvchi",
        "problem": "Makulatura yig'ish aksiyalarida qaysi sinf qancha topshirgani qog'ozda yuritiladi va qiziqish tez so'nadi.",
        "users": "Sinflar, eko-klub, maktab ma'muriyati",
        "features": [
            "Mas'ul topshirilgan hajmni kiritadi: sinf, tur (qog'oz, plastik, batareya), kg",
            "Sinflar reytingi, haftalik va umumiy",
            "Saqlangan daraxtlar va CO₂ taxminiy hisobi (formula kodda ko'rsatiladi)",
            "Har dushanba e'lon: o'tgan hafta g'olibi",
        ],
        "commands": ["/start", "/topshirish", "/reyting", "/mening_sinfim", "/natija", "/admin"],
        "tables": [
            "classes: nomi, sinf_rahbari",
            "deposits: class_id, tur, kg, sana, kiritgan_id",
            "factors: tur, daraxt_koeff, co2_koeff",
        ],
        "steps": [
            "1-hafta: sinflar va topshirishni kiritish",
            "2-hafta: reyting va haftalik e'lon",
            "3-hafta: ekologik ta'sir hisobi, grafik rasm (matplotlib)",
            "4-hafta: maktablararo musobaqa rejimi",
        ],
        "bonus": ["Telegram Mini App'da jonli reyting", "Topshirish joylari xaritasi"],
        "skills": ["agregatsiya va reytinglar", "matplotlib grafiklari", "manbali koeffitsientlar bilan ishlash"],
        "money": "Qayta ishlash kompaniyalari homiyligi; tuman bo'yicha musobaqa tashkil qilish.",
    },
]

GENERAL = {
    "stack": [
        "Python 3.11+ va aiogram 3 — Telegram bot uchun",
        "SQLite — ma'lumotlar bazasi (o'rnatish shart emas)",
        "Git va GitHub — kodni saqlash va jamoada ishlash",
        "Namuna kod: ustozbot/ papkasi — buyruqlar, eslatmalar, tariflar qanday yozilganini ko'ring",
    ],
    "start": [
        "BotFather'da yangi bot yarating va tokenni oling (tokenni hech kimga bermang, GitHub'ga yuklamang)",
        "pip install aiogram; tokenni BOT_TOKEN muhit o'zgaruvchisiga yozing",
        "Avval /start ga javob beradigan eng oddiy botni ishga tushiring",
        "Har haftaning oxirida ishlaydigan versiyani o'qituvchiga ko'rsating",
    ],
    "rubric": [
        ("Ishlaydi", 30, "Rejadagi asosiy funksiyalar xatosiz ishlaydi"),
        ("Kod sifati", 20, "Fayllarga bo'lingan, tushunarli nomlar, izohlar"),
        ("Ma'lumotlar bazasi", 15, "Jadvallar rejaga mos, ma'lumot qayta ishga tushirilganda saqlanadi"),
        ("Foydalanuvchi tajribasi", 15, "Tushunarli xabarlar, tugmalar, xatoda yordam matni"),
        ("Taqdimot", 10, "Muammo, yechim, jonli namoyish 5 daqiqada"),
        ("Bonus", 10, "Kamida bitta bonus vazifa bajarilgan"),
    ],
}
